# Copyright (c) 2025 Indicio
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# This software may be modified and distributed under the terms
# of either the Apache License, Version 2.0 or the MIT license.
# See the LICENSE-APACHE and LICENSE-MIT files for details.

"""
isomdl-uniffi: ISO 18013-5 mobile Driver License implementation with Python bindings

This package provides Python bindings for the Rust-based isomdl-uniffi library,
implementing the ISO 18013-5 standard for mobile Driver Licenses.
"""

__version__ = "0.1.0"

# Import the main module - try multiple paths to handle different wheel structures
_imported = False
_import_error = None

# Try: isomdl_uniffi/isomdl_uniffi.py (generated by maturin for mixed projects)
if not _imported:
    try:
        from .isomdl_uniffi import *
        _imported = True
    except ImportError as e:
        _import_error = e

# Try: isomdl_uniffi/isomdl_uniffi/isomdl_uniffi.py (nested structure)
if not _imported:
    try:
        from .isomdl_uniffi.isomdl_uniffi import *
        _imported = True
    except ImportError:
        pass

if not _imported:
    raise ImportError(
        "Failed to import isomdl_uniffi bindings. "
        "This usually means the Rust library hasn't been built yet. "
        f"Please run './python/precommit/build-bindings.sh' first. "
        f"Original error: {_import_error}"
    )
