name: '[ISOMDL-UNIFFI]: Kotlin Release'

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Artifacts
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: kotlin

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          save-if: false

      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Publish Android
        run: |
          ./gradlew publishAndroidReleasePublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-macos:
    name: Publish to Maven Local on macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: kotlin
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: deps
          save-if: false

      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true

      - name: Install mingw-w64
        run: brew install mingw-w64

      - name: Publish to Github
        run: |
          ./gradlew \
            publishKotlinMultiplatformPublicationToGithubRepository \
            publishJvmPublicationToGithubRepository \
            publishMacosArm64PublicationToGithubRepository \
            publishMacosX64PublicationToGithubRepository \
            publishIosArm64PublicationToGithubRepository \
            publishIosSimulatorArm64PublicationToGithubRepository \
            publishIosX64PublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}